name: Renovate
on:
  workflow_dispatch:
    inputs:
      debug:
        description: Enable debug mode
        type: boolean
        default: false
        required: false

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Load configuration
        id: load_configuration
        run: |
          file=".github/workflows/renovate-product.json"
          echo "file=${file}" >> "${GITHUB_OUTPUT}"
          echo "json<<EOF" >> "${GITHUB_OUTPUT}"
          jq < "${file}" >> "${GITHUB_OUTPUT}"
          echo "EOF" >> "${GITHUB_OUTPUT}"

      - name: Renovate
        uses: renovatebot/github-action@v36.1.1
        with:
          configurationFile: ${{ steps.load_configuration.outputs.file }}
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          LOG_LEVEL: ${{ fromJSON('["warn", "debug"]')[inputs.debug] }}
          RENOVATE_DRY_RUN: ${{ fromJSON('[null, "full"]')[inputs.debug] }}
          RENOVATE_HOST_RULES: |
            [
              {
                  "hostType": "docker"
                , "matchHost": "${{ fromJSON(steps.load_configuration.outputs.json).registries[0] }}"
                , "username": "dgeelen-uipath"
                , "password": "${{ secrets.READ_PACKAGES }}"
              }
            ]
